name: A workflow for my Hello World file
on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hello World"

      - name: touch file
        run: touch file.txt

      - name: set content
        run: echo "Hello World" > file.txt

      - name: cat file
        run: cat file.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: LS
        run: ls -al
